/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS0FNUFVTL0tVTElBSC9TRU1TVEVSIDQvUFdML0JlbGFqYXJBbmd1bGFyL2RlcGxveS1kZW1vL3NyYy9hcHAvYWJvdXQvYWJvdXQuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9EOi9LQU1QVVMvS1VMSUFIL1NFTVNURVIgNC9QV0wvQmVsYWphckFuZ3VsYXIvZGVwbG95LWRlbW8vc3JjL2FwcC9hYm91dC9hYm91dC5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
