/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiRDovS0FNUFVTL0tVTElBSC9TRU1TVEVSIDQvUFdML0JlbGFqYXJBbmd1bGFyL2RlcGxveS1kZW1vL3NyYy9hcHAvbmF2YmFyL25hdmJhci5jb21wb25lbnQuY3NzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0Q6L0tBTVBVUy9LVUxJQUgvU0VNU1RFUiA0L1BXTC9CZWxhamFyQW5ndWxhci9kZXBsb3ktZGVtby9zcmMvYXBwL25hdmJhci9uYXZiYXIuY29tcG9uZW50LmNzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
